# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Water Footprint of agricultural products
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://evgenii.com" # the base hostname & protocol for your site
subpath_url: "/water-footprint/" # name of the subpath for the water footprint subsite

# Build settings
markdown: kramdown

exclude: ['README.md', 'LICENSE']
